### ISSUE TITLE
add  Code of conduct

### ISSUE THREAD

**Issue by satyampgt4** [GDSC-IETDAVV/hacktoberfest_2022#18]
Code of conduct.md is missing

**Comment by satyamgupta1495** [comment]
Hey Satyam, I'd love to work on this one!

**Comment by satyampgt4** [comment]
@satyamgupta1495   you can work on it

**Comment by 26anshgupta** [comment]
#25 kindly check.

**Comment by 26anshgupta** [comment]
Added
#25 Kindly check

**Comment by satyampgt4** [comment]
@26anshgupta   @satyamgupta1495 is already working on this issue
